version: '3.3'

networks:
  portal:
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  mysql_trading:
    image: mysql/mysql-server:8.0.23
    environment:
      MYSQL_DATABASE: trading
      MYSQL_ROOT_PASSWORD: 01!!trading
      MYSQL_ROOT_HOST: '%'    
    networks:
      portal:
        ipv4_address: 172.21.0.5
    ports:
      - '3306:3306'
    #  volumes:
    #    - /data/proto/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=01!!trading
